server:
  port: 9000 # \u7AEF\u53E3

spring:
  application:
    name: gateway-server # \u5E94\u7528\u540D\u79F0
  main:
    web-application-type: reactive

  cloud:
    gateway:
      # \u8DEF\u7531\u89C4\u5219
      routes:
        - id: product-service # \u8DEF\u7531 ID\uFF0C\u552F\u4E00
          uri: http://localhost:7070/ # \u76EE\u6807 URI\uFF0C\u8DEF\u7531\u5230\u5FAE\u670D\u52A1\u7684\u5730\u5740
          predicates: # \u65AD\u8A00\uFF08\u5224\u65AD\u6761\u4EF6\uFF09
            - Path=/product/** # \u5339\u914D\u5BF9\u5E94 URL \u7684\u8BF7\u6C42\uFF0C\u5C06\u5339\u914D\u5230\u7684\u8BF7\u6C42\u8FFD\u52A0\u5728\u76EE\u6807

        - id: order-service
          uri: http://localhost:9090/
          predicates:
            - Path=/order/**