server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka02
  client:
    # \u8868\u793A\u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230 Eureka Server
    fetch-registry: false
    service-url:
      # \u6CE8\u610F\u8FD9\u91CC\u586B\u5199\u5176\u4ED6Eureka\u670D\u52A1\u5668\u7684\u5730\u5740\uFF0C\u4E0D\u7528\u5199\u81EA\u5DF1\u7684
      defaultZone: http://eureka01:8761/eureka